### 1. (Local) Get mod info
GET http://localhost:3001/modInfo
Accept: application/json

### (DEPLOYED) 1. Get mod info
GET https://rest-api-back.vercel.app/modInfo
Accept: application/json

###

### 2. Update mod info (partial update)
PATCH http://localhost:3001/modInfo
Content-Type: application/json

{
  "version": "1.0.0",
  "updateAvailable": false,
  "discordLink": "https://discord.gg/sfNXW3PqQu",
  "enableAll": true,
  "disableAll": false,
  "featureToggles": {
    "farming": true,
    "buyItems": true,
    "buyGear": true,
    "statistics": true,
    "saveInventory": true,
    "recoverInventory": true,
    "sendInventory": true,
    "completeInventory": true
  },
  "dataSyncOptions": {
    "onGameOpenClose": true,
    "onModScreenOpen": true,
    "afterCycle": false,
    "afterOperation": true
  },
  "userValidationOptions": {
    "onGameStart": true,
    "onScreenOpen": true,
    "afterCycle": false,
    "afterOperation": true
  }
}

###

### 4. (Local) Initialize mod info if not exist
POST http://localhost:3001/modInfo/init
Content-Type: application/json

{
  "version": "1.0.0",
  "updateAvailable": false,
  "discordLink": "https://discord.gg/sfNXW3PqQu",
  "enableAll": false,
  "disableAll": false,
  "featureToggles": {
    "farming": false,
    "buyItems": false,
    "buyGear": false,
    "statistics": false,
    "saveInventory": false,
    "recoverInventory": false,
    "sendInventory": false,
    "completeInventory": false
  },
  "dataSyncOptions": {
    "onGameOpenClose": false,
    "onModScreenOpen": false,
    "afterCycle": false,
    "afterOperation": false
  },
  "userValidationOptions": {
    "onGameStart": false,
    "onScreenOpen": false,
    "afterCycle": false,
    "afterOperation": false
  }
}