### 1. (Local) Get all subscribers
GET http://localhost:3001/subscribers
Accept: application/json

### (DEPLOYED) 1. Get all subscribers

GET https://rest-api-back.vercel.app/subscribers
Accept: application/json

###

### 2. Get a specific subscriber by username
GET http://localhost:3000/subscribers/prek1
Accept: application/json

###

### 3. Create a new subscriber
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "username": "prek1",
  "expirationDate": "2024-09-20"
}

###

### 4. Update a subscriber by username
PATCH http://localhost:3000/subscribers/prek5550
Content-Type: application/json

{
  "expirationDate": "2024-12-30"
}

###

### 5. Delete a subscriber by username
DELETE http://localhost:3000/subscribers/prek1

###

### 6. Test endpoint
GET http://localhost:3000/subscribers/test

